services:
  mysql:
    image: mysql:8.0
    container_name: mysql-1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=bankapp
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data: